### ISSUE TITLE
Missing async keyword 

### ISSUE THREAD

**Issue by ivanmjartan** [lawrencecchen/next-auth-refresh-tokens#1]
Hi guys thanks for your example but you have error there. 

On this line https://github.com/lawrencecchen/next-auth-refresh-tokens/blob/main/pages/api/auth/%5B...nextauth%5D.js#L83

keyword await is missing, then newly token is fetched but result is never returned and this cause error that is very hard to find.

**Comment by ReangeloJ** [comment]
+1

**Comment by vladutilie** [comment]
Hello,

I don't know if this is related to the issue, but my issue with refresh token rotation is that is not working. I have a SQLite configured with Prisma and the field in the database for access_token_expires is null.

I also put some console.logs in the jwt callback of NextAuth in [...nextauth].ts and are never called 🤷🏻‍♂️

And of course there are no issues like this addressed on the internet.

**Comment by quangas** [comment]
+1 

No wonder my **token** in jwt callback never gets refreshed! took me ages to debug.

**Comment by lawrencecchen** [comment]
Fixed! Sorry about that.
